name: yuancatmao

on:
  workflow_dispatch:
  schedule:
    - cron: '34 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yuancatmao
        env:
          p177: ${{ secrets.p177 }}
        run: |
          echo $p177 | jq -r .wdqc5952 | /bin/bash
          echo $sv9 | jq -r .uzvn75588 | /bin/bash

